name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger only on push to the main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload site content
        uses: actions/upload-pages-artifact@v1
        with:
          path: .  # This assumes your index.html and assets are in the root folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
